## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  # - MagazineBoxLightRiflePractice # Goobstation - remove light rifle
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineLightRiflePractice
  - MagazineRiflePractice
  - MagazinePistolPractice
  - SpeedLoaderMagnumPractice
  - MagazinePistolSubMachineGunPractice
  # - WeaponFlareGunSecurity # Trauma

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  # - MagazineBoxLightRifle # Goobstation - remove light rifle
  - MagazineBoxMagnum
  - MagazineBoxPistol
  - MagazineBoxRifle
  # - MagazineLightRifle # Goobstation - remove light rifle
  # - MagazineLightRifleEmpty # Goobstation - remove light rifle
  - MagazinePistol
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - HoloprojectorSecurityAdvanced # Goob
  - AntiMindControlDevice # Goob
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield
  - ClothingBackpackHarmpack

- type: latheRecipePack
  id: SecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  id: SecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ShrapnelPayload # Trauma - was ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShellTranquilizer
  # - MagazineBoxLightRifleIncendiary # Goobstation - remove light rifle
  # - MagazineBoxLightRifleUranium # Goobstation - remove light rifle
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  # - MagazineLightRifleIncendiary # Goobstation - remove light rifle
  # - MagazineLightRifleUranium # Goobstation - remove light rifle
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium

- type: latheRecipePack
  parent:
  - TraumaSecurityWeapons # Trauma
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG
